### PR TITLE
New ASCII logo ;)

### PR DESCRIPTION
**Pull request by jaumard**
capture d ecran 2016-01-30 a 15 30 15

### CODE REVIEW

**Comment by nogtini** [comment]
Too cool, any way to preserve the aspect ratio?

**Comment by jaumard** [comment]
Can't manage to keep it :( I use this to convert an image to ascii http://picascii.com then I finish manually. But under the website it keep aspect ratio but when copy paste into trailpack it's not :/  maybe with a better png or something it will be better...

**Comment by jaumard** [comment]
@yejodido did you have a better image (with transparent background and maybe better resolution) ? I can make more test when I have some time :)

**Comment by nogtini** [comment]
trailsbland

**Comment by nogtini** [comment]
trailsbland

**Comment by jaumard** [comment]
Thanks! I play with it a little and to have something like this : 
capture d ecran 2016-02-01 a 20 42 54
I modify your image to look like : 
trailslogolow
It's not perfect but it's better ^^

**Comment by jaumard** [comment]
Last version : 
capture d ecran 2016-02-01 a 21 13 39

**Comment by nogtini** [comment]
Much better!

**Comment by tjwebb** [comment]
How many characters wide is that? We don't want to be more than 80-100 chars wide

**Comment by jaumard** [comment]
It's 155 chars wide. I can remove some space between letters and logo to see if I can have less chars

**Comment by jaumard** [comment]
With the current image I can't make less than 120 chars wide

**Pull request merged**
